version: '2'
services:

  pumba:
    image: gaiaadm/pumba:111-master
    environment:
      http_proxy: "$tb_proxy"
      https_proxy: "$tb_proxy"
      no_proxy: "$tb_no_proxy"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - voteapp
    command: pumba --debug netem --duration 5m delay --time 3000 "re2:(.+)result-app"

networks:
    voteapp:
