version: "2"

services:

  voting-app:
    image: gaiadocker/example-voting-app-vote:${VOTE_TAG}
    environment:
      http_proxy: "$tb_proxy"
      https_proxy: "$tb_proxy"
      no_proxy: "$tb_no_proxy"
    ports:
      - 5000:80
    networks:
      - voteapp

  result-app:
    image: gaiadocker/example-voting-app-result:latest
    environment:
      http_proxy: "$tb_proxy"
      https_proxy: "$tb_proxy"
      no_proxy: "$tb_no_proxy"
    ports:
      - 5001:80
    networks:
      - voteapp

  worker:
    image: gaiadocker/example-voting-app-worker:latest
    environment:
      http_proxy: "$tb_proxy"
      https_proxy: "$tb_proxy"
      no_proxy: "$tb_no_proxy"
    networks:
      voteapp:
        aliases:
          - workers

  redis:
    image: redis:3.2-alpine
    ports:
      - "6379"
    networks:
      - voteapp
    container_name: redis

  db:
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - voteapp
    container_name: db

volumes:
  db-data:
    # driver: rexray
    # driver_opts:
    #  size: 10

networks:
    voteapp:
