version: "2"

services:
  vote:
    build: 
      context: ./vote
      args:
        - https_proxy
        - http_proxy
        - no_proxy
    image: ${DEMO_REP}/example-voting-app-vote:${DEMO_TAG}

  worker:
    build:
      context: ./worker
      args:
        - https_proxy
        - http_proxy
        - no_proxy
    image: ${DEMO_REP}/example-voting-app-worker:${DEMO_TAG}

  result:
    build:
      context: ./result
      args:
        - https_proxy
        - http_proxy
        - no_proxy
    image: ${DEMO_REP}/example-voting-app-result:${DEMO_TAG}

  tests:
    build: 
      context: ./tests
      args:
        - https_proxy
        - http_proxy
        - no_proxy
    image: ${DEMO_REP}/example-voting-app-tests:${DEMO_TAG}
