version: "2"

services:

  voting-app:
    image: gaiaadm/example-voting-app-vote
    ports:
      - 5000:80
    networks:
      - voteapp

  result-app:
    image: gaiaadm/example-voting-app-result
    ports:
      - 5001:80
    networks:
      - voteapp

  worker:
    image: gaiaadm/example-voting-app-worker
    networks:
      voteapp:
        aliases:
          - workers

  redis:
    image: redis:3.2-alpine
    ports:
      - "6379"
    networks:
      - voteapp
    container_name: redis

  db:
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - voteapp
    container_name: db

volumes:
  db-data:
    # driver: rexray
    # driver_opts:
    #  size: 10

networks:
    voteapp:
